webdriverio/visual-testing

- docs/OPTIONS.md
- lib/index.js
- package.json
- tests/configs/wdio.local.autosave.conf.js
- tests/specs/checkMethodsFolders.spec.js
- tests/specs/saveMethodsFolders.spec.js
- folder options can be passed as an object to each method and used to
set the folders used to store baseline, actual, and diff images
> Add the ability to set folder options per method

- lib/tests/__snapshots__/utils.spec.js.snap
- lib/tests/utils.spec.js
- lib/utils.js
- package.json
- tests/configs/wdio.local.desktop.conf.js
- tests/configs/wdio.local.init.conf.js
- tests/configs/wdio.saucelabs.conf.js
- tests/specs/init.spec.js
This adds the feature requested in https://github.com/wswebcreation/webdriver-image-comparison/issues/6 including:
- simplify local config
- add extra test instances for sauce chrome
- add new tests
Last but not least it holds a fix to not always do the customerCSS call that caused issues on FireFox
> **NOTE:** This build will probably break because version `0.7.0` of `webdriver-image-comparison` is not yet released. It waits on 2 PR's
> - https://github.com/wswebcreation/webdriver-image-comparison/pull/28
> - https://github.com/wswebcreation/webdriver-image-comparison/pull/29
> Limit amount of customerCSS calls and add new formatImageName options

- package-lock.json
- package.json
- types/index.d.ts
This PR is adding all the types, so in favour of https://github.com/wswebcreation/wdio-image-comparison-service/pull/26.
It will now even give warnings on the options, see 
and on the output
> feat: add all types

- lib/tests/__snapshots__/utils.spec.js.snap
- lib/tests/utils.spec.js
- lib/utils.js
This fixes issue https://github.com/wswebcreation/wdio-image-comparison-service/issues/61 where Appium W3C caps were not processed properly
> fix: support Appium W3C caps

- docs/CONTRIBUTING.md
- types/index.d.ts
This allows typescript users to use async. Alternatively we could make it Browser<Mode> in the types which would allow either.
I fixed a typo in Contributing which caused some reformatting of the entire file for some reason. Let me know if you want me to remove those changes, they look fine at first glance.
> Change the default type of the browser to BrowserAsync

- .changeset/witty-cats-invite.md
- packages/service/src/service.ts
- packages/service/src/utils.ts
- packages/service/tests/__snapshots__/utils.test.ts.snap
- packages/service/tests/utils.test.ts
This PR fixes the default snapshot path which could not be overwritten by the method/service options
> fix: fix providing the correct baseline path through method/service options

- .husky/pre-commit
- .husky/pre-push
- package.json
Husky was updated to v9 without following the [How to Migrate](https://github.com/typicode/husky/releases/tag/v9.0.1) docs. This is similar to [webdriverio-community/wdio-electron-service#447](https://github.com/webdriverio-community/wdio-electron-service/pull/447).
* Update the `"prepare"` npm script
* Remove the shebang from the Git hooks
> build: Migrate to Husky v9

- .github/workflows/update.yml
* Bump lewagon/wait-on-check-action to 1.3.3 to unblock the Dependabot PRs.
Here is an example from [webdriverio/selenium-standalone](https://github.com/webdriverio/selenium-standalone/actions/runs/7958535376/job/21723602654?pr=876):
```
Installing Bundler
/opt/hostedtoolcache/Ruby/2.7.4/x64/bin/gem install bundler -v ~> 2
ERROR:  Error installing bundler:
The last version of bundler (~> 2) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.4.191.
```
* Bump dependabot/fetch-metadata to 1.6.0
> ci: Update lewagon/wait-on-check-action to fix update workflow

- .github/workflows/update.yml
In order to have dependabot PRs merged automatically we need to allow `skipped` conclusions to the workflows we don't run.
> fix(ci): allow skipped conclusions

- packages/service/src/service.ts
throwing a type exception in node_modules@wdio\visual-service\dist\service.js file in beforeTest hook as it is expecting "filename" not just "file" - the property is from jasmine-core
"* https://github.com/Property {String} filename - The name of the file the spec was defined in."
> Replaced file to filename to match whats running on jasmine-core

- .changeset/itchy-starfishes-tie.md
- packages/visual-service/src/index.ts
- packages/webdriver-image-comparison/src/index.ts
Just making the type import a bit cleaner by exporting the `WicElement` from the package.
> fix(webdriver-image-comparison): export WicElement

- .changeset/large-clouds-confess.md
- packages/ocr-service/src/commands/ocrClickOnText.ts
Fix the click duration if 0 is asked. For example, the default duration (500ms) was applied in this case: 
```
await browser.ocrClickOnText({
text: "WebdriverIO",
clickDuration: 0, // This is 0 seconds
}
```
> fix click duration for 0ms

- .changeset/light-pants-applaud.md
- packages/webdriver-image-comparison/src/commands/checkAppElement.ts
- packages/webdriver-image-comparison/src/commands/checkWebElement.ts
- packages/webdriver-image-comparison/src/helpers/constants.ts
- packages/webdriver-image-comparison/src/methods/images.ts
This PR improves the iPhone support
-   Mobile: support iOS 18 and the iPhone 16 series for the blockouts
-   Mobile: don't use the device blockouts for element screenshot
-   Mobile: when the blockouts had the value `{x: 0, y: 0, width: 0, height: 0}` then Resemble picked this up as a full blockout. This caused false positives for iOS
>  Improve iPhone support

- .changeset/happy-laws-brake.md
- packages/visual-service/package.json
- pnpm-lock.yaml
In #766 `node-fetch` was removed but forgotten from the dependencies. This removes it completely as it's unused.
> chore: remove node-fetch completely

- .gitignore
- package.json
- pnpm-lock.yaml
- vitest.config.ts
While working on another features, I noticed it was quite hard to see the errors with the default reporter for Vitest.
This PR adds VitestUI and improves the Vitest config.
- Bump Vitest packages to latest version (I followed the [migration guide](https://vitest.dev/guide/migration.html#vitest-3))
- Add VitestUI with a `test:unit:ui` command
- Cleaned up the current Vitest config
- Some old leftovers
- Leverage Vitest default configs
- Unrelated changes to `package.json` - pnpm automatically fixed the sorting on the packages
<details>
<summary>Current config (vitest v2) output</summary>
```
> vitest --coverage --run
RUN  v2.1.9
Coverage enabled with v8
✓ packages/ocr-service/tests/utils/imageProcessing.test.ts (9 tests) 11ms
✓ packages/ocr-service/tests/commands/tesseract.test.ts (24 …
```
> chore: bump vitest and add vitest ui

- packages/visual-service/src/service.ts
- packages/webdriver-image-comparison/src/clientSideScripts/hideRemoveElements.ts
- packages/webdriver-image-comparison/src/methods/elementPosition.ts
- packages/webdriver-image-comparison/src/methods/instanceData.ts
- packages/webdriver-image-comparison/src/methods/methods.interfaces.ts
- packages/webdriver-image-comparison/src/methods/screenshots.ts
While trying to implement `@wdio/eslint` I noticed that `Executor` type was loosely defined, this should now infer the correct type from the function that is passed.
With the type inference, we can remove some castings.
> chore: improve executor type

- packages/visual-service/src/storybook/utils.ts
A small improvement to infer the type from the `parseFunc` of the `getArgvValue()` function.
> chore: improve `getArgvValue` return type

- .github/workflows/tests.yml
Pull requests titles that include backticks will make the CI fail because they are evaluated as valid bash characters, surrounding it with double quotes should force it to be a string.
Also removing the deprecated `::set-output` ([docs](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#patching-your-actions-and-workflows))
> ci: fix backtick parsing

- .changeset/early-timers-crash.md
- README.md
- packages/visual-service/src/storybook/Types.ts
- packages/visual-service/src/storybook/launcher.ts
- packages/visual-service/src/storybook/utils.ts
- packages/visual-service/tests/storybook/__snapshots__/utils.test.ts.snap
- packages/visual-service/tests/storybook/launcher.test.ts
- packages/visual-service/tests/storybook/utils.test.ts
- packages/webdriver-image-comparison/src/helpers/options.interfaces.ts
This adds the feature to include additional search params to the Storybook URL. 
This is very useful when you have for example different themes using the CSS Variables Theme addon ([docs](https://github.com/etchteam/storybook-addon-css-variables-theme?tab=readme-ov-file#set-a-theme-by-query-string)) or if we want to use Controls on a specific story (`&args=myControl:updateValue`).
> feat: add `additionalSearchParams` API to Storybook Runner

- packages/webdriver-image-comparison/src/methods/images.ts
Current `saveBase64Image` is a synchronous function as it's using only `fs` synchronous API.
This PR updates the definition of the function to be sync only and its uses.
> chore: update `saveBase64Image` to use promises

- .github/workflows/alpha.release.yml
- .github/workflows/deploy-visual-reporter.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- README.md
- package.json
Enable the setup of the project using `corepack` to install a specific version of `pnpm`.  
This improves consistency between contributors and makes it easier for new contributors to get started with the project.
Reference: https://pnpm.io/installation#using-corepack
> chore: setup pnpm using corepack

- README.md
In #782 I forgot to add docs to the config part and the `New Custom Command` section.
> docs: add more examples of additionalSearchParams

- packages/visual-service/package.json
- packages/visual-service/src/index.ts
- packages/visual-service/tsconfig.json
- pnpm-lock.yaml
While working on bumping ESLint, the `any` from this interface was causing some issues.
This type is a duplicate of the one already in `expect-webdriverio`. As we actually already include this package, this should not have any impact, and actually make it more clear that `visual-service` extends the matchers.
```bash
$ pnpm why expect-webdriverio
@wdio/visual-service link:packages/visual-service
└─┬ @wdio/globals 9.9.1
└── expect-webdriverio 5.1.0
```
> chore: remove duplicated expect-webdriverio type

- README.md
Links FAQs to the new link and corrects the file path
Fixes https://github.com/webdriverio/webdriverio/issues/14345
> chore(README.md): fix links

- packages/webdriver-image-comparison/package.json
- packages/webdriver-image-comparison/tsconfig.json
- pnpm-lock.yaml
`copy-files` dependency was just used to include the `resemble.jimp.cjs` file in the bundle.
This can be achieved using `allowJs` and `include` in `tsconfig.json`
> chore: remove copy-files dependency

- .changeset/hot-carrots-appear.md
- packages/webdriver-image-comparison/src/commands/saveWebElement.ts
> fix: fix capturing non-static positioned elements via bidi interface

- .changeset/upset-areas-wear.md
- packages/visual-service/src/service.ts
This PR is a fix for [issue 983](https://github.com/webdriverio/visual-testing/issues/983).
---
In the previous version of the code, the functions was added first to each instance of the browser and then to the browser object.
The problem is, `@wdio\utils\build\index.js` (line 388) already add the command to each instance so the commande added to each instance was overwritten by the one containing the loop of each instance.
---
Change the addCommand order for Multi Remote
- first, add the command to Browser in a Multi Remote version (with a loop to do the function in each instance)
- then, add the command to each instance in a Single Remote version 
For ocr-service
> Issue 983 for main

- packages/image-comparison-core/src/helpers/afterScreenshot.interfaces.ts
- packages/visual-service/src/storybook/utils.ts
- tests/specs/checkMethodsFolders.spec.ts
- tests/specs/multiremote.spec.ts
- tests/specs/saveMethodsFolders.spec.ts
> chore: fix typos
